$default_network_interface = `ip route | grep -E "^default" | awk '{printf "%s", $5; exit 0}'`


Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.network "public_network", bridge: "#$default_network_interface"
  config.vm.provider "virtualbox" do |vb|
  vb.memory = 8000
  vb.cpus = 2
  vb.name = "kali-linux-2020"

  vb.customize ["modifyvm", :id, "--usb", "on"]
  vb.customize ["modifyvm", :id, "--usbehci", "off"]
  vb.gui = true
  vb.customize ['setextradata', :id, 'GUI/ScaleFactor', '2.00']
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
